### ISSUE TITLE
'자바스크립트로 함수형 프로그래밍 아주 살짝 맛보기' 포스트내 링크 문제

### ISSUE THREAD

**Issue by Seojiwoong** [adhrinae/gatsby-blog#1]
'자바스크립트로 함수형 프로그래밍 아주 살짝 맛보기'  포스트 내에

관심을 가지고 있는 분야 리스트에 '테스팅'이 있고 거기에 https://emaren84.github.io/posts/what-is-testing-javascript-kr로 링크를 걸어두셨던데

https://emaren84.github.io/posts/what-is-testing-javascript-kr 로 이동되는게 아니라
https://emaren84.github.io/https://emaren84.github.io/posts/what-is-testing-javascript-kr 로 이동되어버리네요

gatsby 로 만들어진 다른사이트에서도 테스트해보니 동일한 도메인을 가진 링크로 이동할경우에 도메인주소 + 링크 주소로 이동되어버리네요

gatsby 자체 버그인지 아니면 다른문제인지는 잘모르겠습니다 제가 gatsby 를 전혀 써본적이없어서...

블로그 잘보고있습니다. 감사합니다

**Comment by adhrinae** [comment]
제보 감사합니다. 블로그 원고는 개인 노트 앱에 마크다운으로 작성하고 gatsby 앱으로 옮기고만 있는데, 도메인 인식 문제가 여러번 있던걸 뒤늦게 확인해서 수동으로 고치고 있습니다.

아마 아예 다른 사이트는 외부 링크로 인식을 하는데 제 블로그 도메인이 달려있으면 저렇게 추가 링크가 달리더군요. 요즘에는 어떤지 패키지 업데이트라도 해보고 확인해야겠습니다.

말씀하신 부분은 오늘이나 내일 중으로 수정하고 이슈를 닫겠습니다.
